services:
  miner-api:
    image: redteamsubnet61/flowradar-submission_template:latest
    build:
      context: .
    restart: unless-stopped
    platform: linux/amd64
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
    ports:
      - 10002:10002
    tty: true
